### ISSUE TITLE
grafcli depends on elasticsearch even if its configuration don't have elasticsearch backend

### ISSUE THREAD

**Issue by t2y** [m110/grafcli#10]
Is this a bug?

* https://github.com/m110/grafcli/blob/master/grafcli/storage/elastic.py#L4

```ini
(grafana) $ cat .grafcli.conf 
[grafcli]
# Your favorite editor - this name will act as a command!
editor = vim
# Commands history file. Leave empty to disable.
history = ~/.grafcli_history
# Additional verbosity, if needed.
verbose = off
# Answer 'yes' to all overwrite prompts.
force = on

[resources]
# Directory where all local data will be stored (including backups).
data-dir = ~/.grafcli

# List of remote Grafana hosts.
# The key names do not matter, as long as matching section exists.
# Set the value to off to disable the host.
[hosts]
mysql.example.com = on

[mysql.example.com]
type = mysql
host = mysql.example.com
port = 3306
user = grafana
password =
database = grafana
```

```bash
(grafana) $ pip freeze
climb==0.3.1
grafcli==0.4.5
mysqlclient==1.3.9
urllib3==1.19.1
(grafana) $ grafcli --version
Traceback (most recent call last):
  File "path/to/.virtualenvs/grafana/bin/grafcli", line 5, in <module>
    from grafcli.core import GrafCLI
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/__init__.py", line 1, in <module>
    from .core import GrafCLI
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/core.py", line 5, in <module>
    from grafcli.commands import GrafCommands
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/commands.py", line 14, in <module>
    from grafcli.resources import Resources
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/resources/__init__.py", line 1, in <module>
    from grafcli.resources.resources import Resources
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/resources/resources.py", line 5, in <module>
    from grafcli.resources.remote import RemoteResources
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/resources/remote.py", line 1, in <module>
    from grafcli.storage import get_remote_storage
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/storage/__init__.py", line 5, in <module>
    from grafcli.storage.elastic import ElasticStorage
  File "path/to/.virtualenvs/grafana/lib/python3.5/site-packages/grafcli/storage/elastic.py", line 4, in <module>
    from elasticsearch import Elasticsearch
ImportError: No module named 'elasticsearch'
```

**Comment by m110** [comment]
Yeah, it's some poor design in loading the storage backends. I'll get on that, thanks for reporting!
