### ISSUE TITLE
grafcli-0.4.6 run fail on python2.7

### ISSUE THREAD

**Issue by mars00772** [m110/grafcli#12]
root@ubuntu:/mnt/hgfs/grafcli-0.4.6# grafcli -h     
Traceback (most recent call last):
  File "/usr/local/bin/grafcli", line 5, in <module>
    pkg_resources.run_script('grafcli==0.4.6', 'grafcli')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/grafcli-0.4.6-py2.7.egg/EGG-INFO/scripts/grafcli", line 5, in <module>
    from grafcli.core import GrafCLI
  File "/usr/local/lib/python2.7/dist-packages/grafcli-0.4.6-py2.7.egg/grafcli/__init__.py", line 1, in <module>
    from .core import GrafCLI
  File "/usr/local/lib/python2.7/dist-packages/grafcli-0.4.6-py2.7.egg/grafcli/core.py", line 5, in <module>
    from grafcli.commands import GrafCommands
  File "/usr/local/lib/python2.7/dist-packages/grafcli-0.4.6-py2.7.egg/grafcli/commands.py", line 12, in <module>
    from grafcli.documents import Document, Dashboard, Row, Panel
  File "/usr/local/lib/python2.7/dist-packages/grafcli-0.4.6-py2.7.egg/grafcli/documents.py", line 37
    class Document(object, metaclass=ABCMeta):
                                    ^
SyntaxError: invalid syntax

**Comment by m110** [comment]
Grafcli was written with python3 in mind from the beggining. Please use it if you can, it should be enough to install it on your server.
