### ISSUE TITLE
Can not install using pip

### ISSUE THREAD

**Issue by aksyonov** [m110/grafcli#18]
```
~$ sudo pip3 install grafcli
Downloading/unpacking grafcli
  Downloading grafcli-0.5.6.tar.gz
  Running setup.py (path:/tmp/pip-build-ek06y4s7/grafcli/setup.py) egg_info for package grafcli
    fatal: Not a git repository (or any parent up to mount point /tmp)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-ek06y4s7/grafcli/setup.py", line 5, in <module>
        git_version = check_output(["git", "describe", "--tags"]).strip().decode()
      File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
        raise CalledProcessError(retcode, process.args, output=output)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any parent up to mount point /tmp)

Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-ek06y4s7/grafcli/setup.py", line 5, in <module>

    git_version = check_output(["git", "describe", "--tags"]).strip().decode()

  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output

    raise CalledProcessError(retcode, process.args, output=output)

subprocess.CalledProcessError: Command '['git', 'describe', '--tags']' returned non-zero exit status 128
```

**Comment by m110** [comment]
Thanks for the report @aksyonov, version 0.5.9 should be installing fine now!
