### ISSUE TITLE
Getting KeyError when trying to backup dashboards

### ISSUE THREAD

**Issue by deepakhj** [m110/grafcli#4]
I'm getting a KeyError when trying to backup all dashboards. Any ideas?

```python
[/]> backup remote/localhost ~/backup.tgz
Traceback (most recent call last):
  File "/usr/local/bin/grafcli", line 27, in <module>
    sys.exit(main())
  File "/usr/local/bin/grafcli", line 22, in main
    cli.run()
  File "/usr/local/lib/python3.4/dist-packages/climb/core.py", line 55, in run
    result = self.execute(*shlex.split(command))
  File "/usr/local/lib/python3.4/dist-packages/climb/core.py", line 73, in execute
    return self._commands.execute(command, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/climb/commands.py", line 26, in execute
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/commands.py", line 173, in backup
    self.file_export(doc_path, file_path)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/commands.py", line 204, in file_export
    document = self._resources.get(path)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/resources/resources.py", line 46, in get
    return manager.get(*parts)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/resources/common.py", line 33, in get
    dashboard = self._storage.get(dashboard_name)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/storage/sql.py", line 72, in get
    return Dashboard(source, dashboard_id)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 96, in __init__
    self._load(source)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 103, in _load
    self._add_row(row)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 131, in _add_row
    row = Row(source, max_id+1, self)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 173, in __init__
    self._load(source, id)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 182, in _load
    self._add_panel(panel, keep_id=True)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 226, in _add_panel
    panel = Panel(source, id, self)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 276, in __init__
    self._load(source)
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 281, in _load
    self._name = "{}-{}".format(self._id, slug(self.title))
  File "/usr/local/lib/python3.4/dist-packages/grafcli/documents.py", line 84, in title
    return self._source['title']
KeyError: 'title'

**Comment by m110** [comment]
Hey, sorry for such long time without a response. Looks like one of the panels is missing a title. Perhaps the backend should be corrected to handle it properly.

**Comment by m110** [comment]
So I looked into it and it seems that Grafana won't let you delete the title field from panel document. My guess is it was removed manually and that caused this error. I know that it's been a long time since that report, so please let me know if it still occurs.
